services:
    api:
        container_name: api
        build: .
        volumes:
            - ./:/var/www
        restart: always
    nginx_api:
        container_name: nginx_api
        build:
            context: infrastructure/nginx
            dockerfile: Dockerfile
        ports:
            - '3030:3030'
        restart: always
